# Generated by Django 5.1.2 on 2024-10-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('it', 'IT Department'), ('hr', 'Human Resources'), ('facilities', 'Facilities Management'), ('legal', 'Legal Department'), ('academic', 'Academic Department'), ('operations', 'Operations'), ('security', 'Security'), ('general', 'General')], max_length=50),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('user', 'Regular User'), ('staff', 'Department Staff'), ('admin', 'Department Admin')], default='user', max_length=10),
        ),
    ]
