# Generated by Django 5.1.2 on 2024-11-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_department_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('technical', 'Technical Support'), ('hr', 'HR Related Issues'), ('facility', 'Facility Management'), ('security', 'Security Issues'), ('academic', 'Academic Matters'), ('financial', 'Financial Concerns'), ('general', 'General Inquiries')], max_length=50),
        ),
    ]
