# Generated by Django 5.1.2 on 2024-11-03 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grievances', '0003_comment_escalation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grievance',
            options={'ordering': ['-created_at']},
        ),
    ]
