# Generated by Django 5.1.2 on 2024-11-01 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_statusupdate'),
        ('grievances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='statusupdate',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grievances.grievance'),
        ),
        migrations.AddField(
            model_name='statusupdate',
            name='updated_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
