# Generated by Django 5.1.2 on 2024-11-02 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0003_statusupdate_grievance_statusupdate_updated_by'),
        ('grievances', '0003_comment_escalation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='statusupdate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='statusupdate',
            name='grievance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='grievances.grievance'),
        ),
    ]
