# Generated by Django 5.1.3 on 2025-05-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0004_alter_statusupdate_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='head',
        ),
        migrations.AlterField(
            model_name='departmentstaff',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='departments.department'),
        ),
    ]
